import type { Metadata } from "next";
import { Poppins } from "next/font/google";

import "@/styles/globals.css";
import '@iconscout/unicons/css/line.css';

import { Header } from "@/components/header";

const geisPoppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
})

export const metadata: Metadata = {
  title: "Gelzieny.dev",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${geisPoppins.variable}  antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
